#!/usr/bin/env python3
"""
Generate a markdown index of MD files and their chunks from data/corpus.jsonl.

Usage:
  python tools/gen_md_chunk_index.py > docs/MD_CHUNKS_INDEX.md
"""

from __future__ import annotations

import json
import os
import sys
from collections import defaultdict


def _load_corpus(path: str) -> list[dict]:
    rows: list[dict] = []
    with open(path, "r", encoding="utf-8") as f:
        for raw in f:
            line = raw.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
            except json.JSONDecodeError:
                continue
            if isinstance(obj, dict):
                rows.append(obj)
    return rows


def _safe_str(x) -> str:
    return "" if x is None else str(x)


def main() -> int:
    # Ensure UTF-8 output even on Windows cp1251 consoles / redirection.
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass
    # Add UTF-8 BOM so editors/tools decode correctly on Windows.
    sys.stdout.write("\ufeff")
    root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
    corpus_path = os.path.join(root, "data", "corpus.jsonl")
    rows = _load_corpus(corpus_path)

    by_file: dict[str, list[dict]] = defaultdict(list)
    for r in rows:
        f = _safe_str(r.get("file")).strip()
        if not f:
            continue
        by_file[f].append(r)

    print("# MD -> chunks index")
    print()
    print(f"Source: `data/corpus.jsonl` ({len(rows)} chunks)")
    print()
    print("> Generated by `tools/gen_md_chunk_index.py`.")
    print()

    for md_file in sorted(by_file.keys()):
        chunks = by_file[md_file]
        # Stable order: korotko first, then by h3_id, then by h2/h3
        def _key(c: dict):
            h3_id = _safe_str(c.get("h3_id")).strip().lower()
            return (0 if h3_id == "korotko" else 1, h3_id, _safe_str(c.get("h3")).lower())

        chunks_sorted = sorted(chunks, key=_key)
        doc_id = _safe_str(chunks_sorted[0].get("doc") or os.path.splitext(md_file)[0]).strip()
        topic = _safe_str(chunks_sorted[0].get("topic")).strip()
        doc_type = _safe_str(chunks_sorted[0].get("doc_type")).strip()
        subtype = _safe_str(chunks_sorted[0].get("subtype")).strip()

        print(f"## `{md_file}`")
        meta_bits = [f"doc_id=`{doc_id}`"]
        if topic:
            meta_bits.append(f"topic=`{topic}`")
        if doc_type:
            meta_bits.append(f"doc_type=`{doc_type}`")
        if subtype:
            meta_bits.append(f"subtype=`{subtype}`")
        print("- " + ", ".join(meta_bits))
        print()

        for c in chunks_sorted:
            h3 = _safe_str(c.get("h3")).strip() or "(no h3)"
            h3_id = _safe_str(c.get("h3_id")).strip()
            h2 = _safe_str(c.get("h2")).strip()
            snippet = _safe_str(c.get("text")).strip().replace("\n", " ")
            snippet = (snippet[:160] + "…") if len(snippet) > 160 else snippet
            aliases = c.get("aliases") if isinstance(c.get("aliases"), list) else []
            alias_n = len([a for a in aliases if isinstance(a, str) and a.strip()])

            anchor = f"#{h3_id}" if h3_id else ""
            where = f"`{md_file}{anchor}`" if anchor else f"`{md_file}`"
            line = f"- **{h3}** ({where}"
            if h2:
                line += f", h2={h2!r}"
            if alias_n:
                line += f", aliases={alias_n}"
            line += ")"
            print(line)
            if snippet:
                print(f"  - {snippet}")
        print()

    return 0


if __name__ == "__main__":
    raise SystemExit(main())

